spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 12345
        url: jdbc:mysql://localhost:3306/mobilelele?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        hibernate:
            ddl-auto: create-drop
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
